// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PqsTracker.Data;

#nullable disable

namespace PqsTracker.Data.Migrations
{
    [DbContext(typeof(PqsDbContext))]
    [Migration("20260917183348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("PqsTracker.Models.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("PqsTracker.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("PqsTracker.Models.SignOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineItemId");

                    b.HasIndex("QualifierId");

                    b.HasIndex("TraineeId");

                    b.ToTable("SignOffs");
                });

            modelBuilder.Entity("PqsTracker.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("QualificationTrainee", b =>
                {
                    b.Property<int>("HeldQualificationsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolderTraineesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeldQualificationsId", "HolderTraineesId");

                    b.HasIndex("HolderTraineesId");

                    b.ToTable("TraineeQualifications", (string)null);
                });

            modelBuilder.Entity("PqsTracker.Models.LineItem", b =>
                {
                    b.HasOne("PqsTracker.Models.Qualification", "Qualification")
                        .WithMany("LineItems")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("PqsTracker.Models.SignOff", b =>
                {
                    b.HasOne("PqsTracker.Models.LineItem", "LineItem")
                        .WithMany("SignOffs")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PqsTracker.Models.Trainee", "Qualifier")
                        .WithMany("SignOffsGiven")
                        .HasForeignKey("QualifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PqsTracker.Models.Trainee", "Trainee")
                        .WithMany("SignOffsReceived")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineItem");

                    b.Navigation("Qualifier");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("QualificationTrainee", b =>
                {
                    b.HasOne("PqsTracker.Models.Qualification", null)
                        .WithMany()
                        .HasForeignKey("HeldQualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PqsTracker.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("HolderTraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PqsTracker.Models.LineItem", b =>
                {
                    b.Navigation("SignOffs");
                });

            modelBuilder.Entity("PqsTracker.Models.Qualification", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("PqsTracker.Models.Trainee", b =>
                {
                    b.Navigation("SignOffsGiven");

                    b.Navigation("SignOffsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
